import Head from "next/head";
import { Inter } from "next/font/google";
import Welcome from "@/components/funcional/Welcome";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Gaman</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Welcome />
    </>
  );
}
